### ISSUE TITLE
"context" does not work as expected

### ISSUE THREAD

**Issue by Helloburp** [TheNexusAvenger/Nexus-Unit-Testing-Plugin#4]
Hello; I've recently been testing features from the [official testEZ documentation](https://roblox.github.io/testez/api-reference/) and realized that I cannot get the "context" table to work with the plugin's implementation of testEZ.

Here's my example case, where I expect "Bar" to be printed:
![image](https://github.com/user-attachments/assets/52326e5b-8817-43f7-a1fe-713c10f781bb)

In the official package which I got from Wally (roblox/testez@0.4.1), this prints as expected:
![image](https://github.com/user-attachments/assets/9f1c47cf-5475-4a8e-aca7-abe7417efd23)

However, the plugin prints nil:
![image](https://github.com/user-attachments/assets/7d3a4665-fc06-498d-8995-128bf0102448)

If more info is needed, I'll do what I can. Aside from this issue, I've been enjoying using this plugin a lot. Hope this can be resolved easily!

**Comment by TheNexusAvenger** [comment]
I think this bug is due to [how Nexus Unit Testing handles child tests](https://github.com/TheNexusAvenger/Nexus-Unit-Testing/blob/master/src/UnitTest/UnitTest.lua#L220-L302) to contain the test output. I'll try to get it resolved within the next, but for now, I'd suggest against using `context`. While type-checking is less important for test code, using local variables will give you better autocomplete since `context` has no type information.

![image](https://github.com/user-attachments/assets/061cc3e2-0c7f-47a7-9f65-5af50bb003d2)

**Comment by TheNexusAvenger** [comment]
Fixed in V.1.5.1.
